export const users = [
  {
    createdAt: "Sylvia Hettinger",
    name: "Allen Labadie",
    DoB: "1944-08-09T18:07:10.805Z",
    work: "Central Accountability Developer",
    email: "Martin23@yahoo.com",
    id: "1",
  },
  {
    createdAt: "Kerry Casper II",
    name: "Cecilia Okuneva",
    DoB: "1960-10-25T15:48:16.119Z",
    work: "Global Brand Facilitator",
    email: "Nicolas_Okuneva@yahoo.com",
    id: "2",
  },
  {
    createdAt: "Fernando Bergnaum",
    name: "Lonnie Ruecker",
    DoB: "1977-07-27T14:23:14.749Z",
    work: "Principal Integration Officer",
    email: "Alejandrin.Kautzer@yahoo.com",
    id: "3",
  },
  {
    createdAt: "Salvatore Runolfsson",
    name: "Johnnie Blanda DVM",
    DoB: "1981-04-08T09:43:01.903Z",
    work: "Future Branding Developer",
    email: "Sandrine.Funk94@yahoo.com",
    id: "4",
  },
  {
    createdAt: "Mr. Leroy McDermott",
    name: "Bethany Kreiger",
    DoB: "1974-07-16T21:37:50.432Z",
    work: "Investor Intranet Facilitator",
    email: "Beverly.Jaskolski@hotmail.com",
    id: "5",
  },
  {
    createdAt: "Boyd Gerlach",
    name: "Johnathan Purdy",
    DoB: "1991-09-13T09:49:36.959Z",
    work: "Customer Security Analyst",
    email: "Josianne_Will@hotmail.com",
    id: "6",
  },
  {
    createdAt: "Ed Marquardt",
    name: "Terri Hessel",
    DoB: "1988-02-02T18:13:08.191Z",
    work: "Product Branding Associate",
    email: "Percival63@yahoo.com",
    id: "7",
  },
  {
    createdAt: "Nina Dibbert",
    name: "Dr. Kathryn Medhurst PhD",
    DoB: "1950-11-14T01:22:08.497Z",
    work: "Principal Data Associate",
    email: "Destinee_Heller45@gmail.com",
    id: "8",
  },
  {
    createdAt: "Mamie Franey",
    name: "Nicholas Adams",
    DoB: "1963-03-14T19:31:11.971Z",
    work: "Regional Assurance Analyst",
    email: "Andy.Douglas44@hotmail.com",
    id: "9",
  },
  {
    createdAt: "Shawn Cartwright",
    name: "Lois Keebler",
    DoB: "1984-08-30T19:13:58.326Z",
    work: "Senior Functionality Orchestrator",
    email: "Llewellyn.Weber63@yahoo.com",
    id: "10",
  },
  {
    createdAt: "Estelle Williamson",
    name: "Lula Dickens",
    DoB: "1966-03-13T15:47:09.721Z",
    work: "Global Group Engineer",
    email: "Dudley_Stanton11@hotmail.com",
    id: "11",
  },
];
